version: '3.9'

services:
  rabbitmq:
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: 'ecommerce-secret-cookie'
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  migrate:
    build:
      context: .
      args:
        SERVICE: user-service
    command: sh -c "npx prisma migrate deploy"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce
    depends_on:
      postgres: { condition: service_healthy }
    restart: 'no'

  api-gateway:
    build:
      context: .
      args:
        SERVICE: api-gateway
    command: npx nest start api-gateway --watch
    ports: ['3000:3000']
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      RABBITMQ_URL: amqp://rabbitmq:5672
      JWT_SECRET: it_is_hard_to_earn_money_in_covid_times

    depends_on:
      rabbitmq: { condition: service_healthy }
      migrate: { condition: service_completed_successfully }
    restart: unless-stopped

  user-service:
    build:
      context: .
      args:
        SERVICE: user-service
    command: npx nest start user-service --watch
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      postgres: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
      migrate: { condition: service_completed_successfully }
    restart: unless-stopped

  catalog-service:
    build:
      context: .
      args:
        SERVICE: catalog-service
    command: npx nest start catalog-service --watch
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3002
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      postgres: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
      migrate: { condition: service_completed_successfully }
    restart: unless-stopped

  order-service:
    build:
      context: .
      args:
        SERVICE: order-service
    command: npx nest start order-service --watch
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3003
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      postgres: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
      migrate: { condition: service_completed_successfully }
    restart: unless-stopped

  payment-service:
    build:
      context: .
      args:
        SERVICE: payment-service
    command: npx nest start payment-service --watch
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3004
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      postgres: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
      migrate: { condition: service_completed_successfully }
    restart: unless-stopped

  inventory-service:
    build:
      context: .
      args:
        SERVICE: inventory-service
    command: npx nest start inventory-service --watch
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3005
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      postgres: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
      migrate: { condition: service_completed_successfully }
    restart: unless-stopped

  notification-service:
    build:
      context: .
      args:
        SERVICE: notification-service
    command: npx nest start notification-service --watch
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3006
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq: { condition: service_healthy }
      migrate: { condition: service_completed_successfully }
    restart: unless-stopped

  shipping-service:
    build:
      context: .
      args:
        SERVICE: shipping-service
    command: npx nest start shipping-service --watch
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3007
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      postgres: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
      migrate: { condition: service_completed_successfully }
    restart: unless-stopped

volumes:
  rabbitmqdata:
